plugins:
  - import
  - simple-import-sort
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaVersion: 2022
root: true
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
